version: '3.8'

services:
  nginx:
    container_name: blog_nginx
    image: nginx:stable
    volumes:
      - ./src/:/var/www/lar/
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d/:ro
    ports:
      - "8000:80"
    depends_on:
      - app
      - db
  app:
    build:
      context: ./_docker/app/
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/lar/
    container_name: blog_app
  db:
    container_name: blog_db
    image: mysql:8.0
    ports:
      - "5000:3306"
    restart: always
    volumes:
      - ./tmp/db/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: blog_db
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  composer:
    build:
      context: ./_docker/composer/
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/lar
  artisan:
    build:
      context: ./_docker/app/
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/lar
    entrypoint: ["php", "/var/www/lar/artisan"]